### ISSUE TITLE
Love this picker! A small issue

### ISSUE THREAD

**Issue by ynotstartups** [Sphinxxxx/vanilla-picker#1]
Hey Sphinxxxx,

I like this picker and I am using in [my website](https://myminifactory.github.io/stl2gltf/), however there is a small issue in firefox,

I init picker with alpha: false, then in firefox if you drag the slider and picker to the right, you can see a grey boundary line.

<img width="342" alt="screen shot 2018-03-20 at 21 38 18" src="https://user-images.githubusercontent.com/13963732/37684236-470789e4-2c87-11e8-8af8-9c65dd76c40b.png">

**Comment by Sphinxxxx** [comment]
Thanks!

I see. Looks related to this Firefox bug/feature: https://stackoverflow.com/questions/28009963/firefox-css-outline-bug

Until I get this fixed, you can add this CSS to your page:

    .picker_wrapper::before {
        height: 0;
    }
    .picker_wrapper .picker_hue,
    .picker_wrapper .picker_sl,
    .picker_wrapper .picker_alpha,
    .picker_wrapper .picker_sample {
        outline: none;
        box-shadow: 0 0 0 1px silver;
    }

**Comment by ynotstartups** [comment]
Thanks it works!
