### ISSUE TITLE
Please add CSS prefixes

### ISSUE THREAD

**Issue by petedol87** [Sphinxxxx/vanilla-picker#10]
Hi and thanks for this nice plugin!

Since you 're using flexbox in your CSS, which is not fully backwards compatible, it would be nice if you could add prefixes for increasing CSS-related compatibility. 

I see that you 're using gulp, so the best option to do it (I assume you already know that) is add [gulp-autoprefixer](https://www.npmjs.com/package/gulp-autoprefixer) to your sass gulp task, which will compile e.g. `.picker_wrapper { display:flex; }` to `.picker_wrapper { display:-webkit-box; display:-ms-flexbox; display:flex; }` (or more/less prefixing, according to your 'browsers' setting).

**Comment by Sphinxxxx** [comment]
Thanks, that's a good idea! Will update shortly.
