### ISSUE TITLE
Double onChange event

### ISSUE THREAD

**Issue by robinchew** [Sphinxxxx/vanilla-picker#11]
1. Launch the picker
2. Select a colour
3. onChange event triggers twice

[See demo of issue](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvAHgFcoACCAEwF4AOiABGtAB5DOcYgE9YgkRmoBrAOYAnWmzQ9EABwhplQgHwC0nTiygQT1Gys6EY6mJ2K1OUDNuqFOBiouLAD0NmYWVuFwMLDUxJx0UFrqoeHmlta2MW48WsKwnFrEemwJhon0cLSwabbmoRwmlCAxccQQVXgAzIjdACwgAL4U6Ni4iAQAVghUdAxMxHgQWHq06gkAChBB6pxgmlicAOQAbhho0N4AtIHKLscA3ObmaDAA7pzbuwAUwBkBDCuBiITh5ahsHAMfCqGDEACisChxAAQjIAJI8H7HURiY4ASgoALWpT0oJxtGIHiwxyJkXoAGFCBdYaDqJw+CYAj9qPg9OpDMQABIwMQ-fGE8xDfHmFptGDxTpoBCTACsfQATMNRiBMDg8PhqHBZjR6IxmJNhgBdIZAA)

**Comment by robinchew** [comment]
Fix is to comment out `callbackClick: relayDrag,`. But I don't know if that will cause a regression.

**Comment by Sphinxxxx** [comment]
You are correct! `callbackDragStart` handles the cases which `callbackClick` was meant for.
