### ISSUE TITLE
Hsl : value precision

### ISSUE THREAD

**Issue by mothsART** [Sphinxxxx/vanilla-picker#12]
Hi,

When i use **color.hslString**, result give me too much precision : 

**hsl(355.29411764705884,99.1304347826087%,51.73913043478261%)**

It would be nice to have a function that allows to choose the result after the decimal point or something approching ?

**Comment by Sphinxxxx** [comment]
Hello! Which version do you use? This should have been fixed in v2.7

**Comment by mothsART** [comment]
An old version indeed : 2.6.0.
Sorry

**Comment by Sphinxxxx** [comment]
No worries :)
