### ISSUE TITLE
Destroy the insctance

### ISSUE THREAD

**Issue by trenyture** [Sphinxxxx/vanilla-picker#14]
I am using your awesome plugin with my VueJS app, but I need to prevent memory lacks **to destroy the instance**... And I didn't find the way how to do it in the documentation...

Is there some methods to destroy it? Something like this? 

`
var pick = new Picker(element, options);
...
pick.destroy();
`

**Comment by Sphinxxxx** [comment]
No, currently there's no such method. What would that method have to do? Just remove the picker element from the DOM?

If you call `pick.domElement.remove()`, does that help with the memory leaks? Maybe a few events need cleanup as well.

**Comment by Sphinxxxx** [comment]
Could you make a demo which shows these memory leaks when using Vue?

**Comment by trenyture** [comment]
Ok, I'll try this...

I don't have any examples, the fact is in VueJS documentation it's telling us to be carefull about memory lack using external plugin because the Dom is not totally destroyed, so we should destroy it manually... I think the way you gave me is a good example, I didn't know about it. Thanks

EDIT : 

When i do this, it's saying to me that domElement is undefined ... ? Normal?

2nd EDIT : 

I found the way, `pick.settings.parent.remove()`, thanks for your help :+1:

**Comment by codeclown** [comment]
Nowadays when many people use vdom-style libraries like React or Vue, it is pretty standard to include a destroy-method which can be used before the parent node disappears OR is altered, in which case leaving old event handlers in is not desirable (the thing is that the parent may not be removed from the DOM; it might change purpose completely, though).

In the case of this library it seems to me that the actions that should be done in a destroy-method would be:

- Remove the DOM-elements generated by this library
- Remove any event listeners added to elements outside of the library-generated DOM-elements
  - [`addEvent(parent, ...)`](https://github.com/Sphinxxxx/vanilla-picker/blob/044ec3e255c9485cf2f1f543a39f960abb2a7f4a/src/js/picker.js#L203)
  - [`onKey(parent, ...)`](https://github.com/Sphinxxxx/vanilla-picker/blob/044ec3e255c9485cf2f1f543a39f960abb2a7f4a/src/js/picker.js#L210)
  - [`addEvent(window, ...)` x2](https://github.com/Sphinxxxx/vanilla-picker/blob/044ec3e255c9485cf2f1f543a39f960abb2a7f4a/src/js/picker.js#L459-L460)

Would you accept a PR implementing such a destroy-method?

**Comment by Sphinxxxx** [comment]
@codeclown - Thanks, I've been meaning to fix this for a while! What complicates things a little are two [`addEvent(window, ...)`](https://github.com/Sphinxxxx/vanilla-picker/blob/044ec3e255c9485cf2f1f543a39f960abb2a7f4a/src/js/utils.js#L65,L67) listeners in the `dragTrack()` utils function as well.

If you have a fix, please submit a PR :)
