### ISSUE TITLE
Shadow DOM support

### ISSUE THREAD

**Issue by mattriley** [Sphinxxxx/vanilla-picker#15]
Hi there. I was looking for a "vanillaJS" colour picker and was pleasantly surprised to find this, thank-you!

I'm attempting to use the picker within a "shadow DOM":
https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM

The picker doesn't seem to operate correctly in this scenario.  (it momentarily displays a text field and button before vanishing). I notice there's some code that dynamically creates a style element, and injects it into the document head. I'm wondering if it would be possible to control where the style gets injected so that it could be injected into a shadow DOM.

I've created a gist to demonstrate the scenario at:
https://gist.github.com/mattriley/fe456b6579d6938359266c305fd45a3a

Thanks again and look forward to your reply.

**Comment by Sphinxxxx** [comment]
Interesting!

Accessing the styles can be fixed. I could for example put the style element in a static property (`Picker.StyleElement` or something), so you can clone it and insert it into the shadow DOM. Would that be a good solution?

However, after a little testing I see that there's more work to do to before the picker can be used in a shadow DOM. Stay tuned!

**Comment by mattriley** [comment]
How are you going with this? Is there anything I can do to help?

**Comment by Sphinxxxx** [comment]
Sorry, no progress yet. Sure, if you want to make a pull request with a proposed fix, that would be great! In addition to exposing the injected `style`, some click handlers need to change so the popup doesn't close too early when used in a shadow DOM.

**Comment by mattriley** [comment]
Pull request submitted =)

**Comment by Sphinxxxx** [comment]
After looking at #17, I found a way to fix both issues in one go. Here is how to use the picker in a shadow DOM now:

https://jsfiddle.net/2pzjcsx0/

**Comment by mattriley** [comment]
Works beautifully, thank-you!
