### ISSUE TITLE
onDone not triggering with Popups

### ISSUE THREAD

**Issue by bridalnetwork** [Sphinxxxx/vanilla-picker#17]
Found a small bug - fixed it.
When a popup, onDone never ran, because the popupCloseProxy ran first. So I added a new check:

BEFORE
`var popupCloseProxy = function popupCloseProxy(e) {
                  _this2._ifPopup(function () {
                      return _this2.closeHandler(e);
                  });
              };
              var onDoneProxy = function onDoneProxy(e) {
                  _this2._ifPopup(function () {
                      return _this2.closeHandler(e);
                  });
                  if (_this2.onDone) {
                      _this2.onDone(_this2.colour);
                  }
              };`

AFTER
`var popupCloseProxy = function popupCloseProxy(e) {
                  if (_this2.onDone) {
                      return _this2.onDone(_this2.colour);
                  }
                  _this2._ifPopup(function () {
                      return _this2.closeHandler(e);
                  });
              };
              var onDoneProxy = function onDoneProxy(e) {
                  _this2._ifPopup(function () {
                      return _this2.closeHandler(e);
                  });
                  if (_this2.onDone) {
                      _this2.onDone(_this2.colour);
                  }
              };`

**Comment by Sphinxxxx** [comment]
Thanks, but please read the [documentation](https://vanilla-picker.js.org/gen/Picker.html#onDone__anchor): `onDone` is only called when you click the **Ok** button, and works as intended on the [demo page](https://codepen.io/Sphinxxxx/pen/zRmKBX) under "More options".

If you want to be notified whenever the popup closes (whether *Ok* or click outside), use the `onClose` callback.

Now, if you still think there is a bug, please provide a working example.

**Comment by bridalnetwork** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  I understand all this. Try it on Firefox. OnDone does nothing. Because, it seems, the popup closes first.None of your demo examples included onDone. Just onChange.It works on Chrome.But not on Firefox.My solution was clumsy.I did better. I 'll send you it tomorrow. At home now.Nicholas                                                                                                                                                                        Sent from my BlackBerry — the most secure mobile device — via the Bell Network                                                                                                                                                                           From: notifications@github.comSent: April 16, 2019 2:59 PMTo: vanilla-picker@noreply.github.comReply to: reply@reply.github.comCc: inDev@bridalnetwork.ca; author@noreply.github.comSubject: Re: [Sphinxxxx/vanilla-picker] onDone not triggering with Popups (#17)  Thanks, but please read the documentation: onDone is only called when you click the Ok button, and works as intended on the demo page under "More options".
If you want to be notified whenever the popup closes (whether Ok or click outside), use the onClose callback.
Now, if you still think there is a bug, please provide a working example.

**Comment by Sphinxxxx** [comment]
Well, I stand corrected :)
I see now that it doesn't work in Firefox. Will fix soon!

**Comment by bridalnetwork** [comment]
:)No problem‎.I patched it, but also added some extra stuff,so it's all confused now.Interesting addition‎ (what I did): I use Picker to select colours,which then are entered in a form input. But what if (a) you pick a colour (b) it is entered in your form's field (c) you change the field, manually (type over it) (d) change your mind and Pick again? The second time you open it, the Picker still remembers the original colour value,not the new,edited one. Which is confusing.So I added an option, to pass it not only the initial colour, but also the object in my page that holds the current value of colour. And modified your OpenHandler to check for that and reset the Picker's color on Open.I am passing it a variable, but it could be a class name or dom element too.Anyway, it's a good plugin you made! ‎I suck at JS and I still figured it out ;)If we end up using it on our public,commercial site, I will be happy to pay a license. (right now, we just play with it to create swatches,for our system. )Nicholas                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the Bell network.                                                                                                                                                                                                                From: Andreas BorgenSent: Thursday, April 18, 2019 7:48 AMTo: Sphinxxxx/vanilla-pickerReply To: Sphinxxxx/vanilla-pickerCc: bridalnetwork; AuthorSubject: Re: [Sphinxxxx/vanilla-picker] onDone not triggering with Popups (#17)Well, I stand corrected :)
I see now that it doesn't work in Firefox. Will fix soon!

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Sphinxxxx/vanilla-picker","title":"Sphinxxxx/vanilla-picker","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Sphinxxxx/vanilla-picker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Sphinxxxx in #17: Well, I stand corrected :)\r\nI see now that it doesn't work in Firefox. Will fix soon!"}],"action":{"name":"View Issue","url":"https://github.com/Sphinxxxx/vanilla-picker/issues/17#issuecomment-484541483"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Sphinxxxx/vanilla-picker/issues/17#issuecomment-484541483",
"url": "https://github.com/Sphinxxxx/vanilla-picker/issues/17#issuecomment-484541483",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Sphinxxxx** [comment]
Ok, `onDone` should be fixed now.

Glad to hear you find the picker useful! You may be able to do what you need without any code changes: When the form field is changed manually, just call `picker.setColor()` with the new color value?
