### ISSUE TITLE
Possibility of  having a Cancel button

### ISSUE THREAD

**Issue by arcadius** [Sphinxxxx/vanilla-picker#18]
Hello.
Thank you very much for creating this very flexible color-picker.

We currently have an "OK" button.
It would be good to also have a "Cancel" or "Dismiss" button that will do picker.hide()

Many thanks

Arcadius

**Comment by Sphinxxxx** [comment]
Sure, an opt-in Cancel button should be easy enough to implement. I'll put it on my to-do list. Feel free to submit a pull request in the meantime :)

**Comment by arcadius** [comment]
Thanks for implementing this @Sphinxxxx :+1:
