### ISSUE TITLE
Picker goes beyond color border

### ISSUE THREAD

**Issue by Betalos** [Sphinxxxx/vanilla-picker#19]
Well i noticed an issue with the picker, that it goes beond the picker borders and therefore having not valid colors (using rgba mode)
![picker](https://user-images.githubusercontent.com/16080229/57568516-f52c6100-73d7-11e9-9522-8868f743c257.PNG)

**Comment by Sphinxxxx** [comment]
Did it get that way by giving the picker invalid input (e.g. through `setColor()`), or by dragging the markers around?

**Comment by Betalos** [comment]
@Sphinxxxx I was able to do it by dragging the marker

**Comment by Sphinxxxx** [comment]
Thanks for reporting this! I can see it happening if you "click" the marker from place to place instead of dragging it. Will fix.
