### ISSUE TITLE
New Picker instances in loop bind to last parent

### ISSUE THREAD

**Issue by nozerov** [Sphinxxxx/vanilla-picker#2]
Hello, 
your Picker looks cool, thank you.

I cant handle creating new Picker instances inside loop.
looks like Picker objects have correct parents in object properties but they all bind to last parent - [https://codepen.io/alanhadzh/pen/rrbVoW](url)

**Comment by Sphinxxxx** [comment]
That is a common programming problem when dealing with variables in loops. Read more about it here: https://www.datchley.name/loop-variable-gotcha/

In your case, the (global) variable `k` remains at its last value when the loop has finished, so in the `onChange` handler `pickers[k]` will always be the last picker you made. One solution is to put the picker initialization in a separate function where the id will be a local variable that doesn't interfere with the other pickers:

https://codepen.io/Sphinxxxx/pen/QBRxpZ
