### ISSUE TITLE
How to set custom CSS?

### ISSUE THREAD

**Issue by sabuz** [Sphinxxxx/vanilla-picker#23]
Can you please tell me how use custom CSS, and mofiy markup of the plugin? Also the behavior is weird as described as https://github.com/Sphinxxxx/vanilla-picker/issues/8

**Comment by Sphinxxxx** [comment]
It depends what you want to do:
* If you just want to do small changes, you can find the CSS class names you need to address in [index.pug](https://github.com/Sphinxxxx/vanilla-picker/blob/master/src/index.pug)
* If you want to change the whole layout, pass a string (e.g. "foo") in `options.layout`. This will add a `layout_foo` class to the picker element which lets you build the picker UI.
  - *If you want a different placement of the popup than the default top/left/bottom/right, you can pass your own string (e.g. "bar") in `options.popup`, which gives you a `popup_bar` class to play with.*
  - Here is an example using CSS Grid: https://jsfiddle.net/m2pdv01c/

**Comment by Sphinxxxx** [comment]
Closing this if there are no more questions..
