### ISSUE TITLE
Clicking off the color picker to close it doesn't fire onDone

### ISSUE THREAD

**Issue by proevilz** [Sphinxxxx/vanilla-picker#3]
When you launch the color picker, then click off screen somewhere to close the color picker, it doesn't fire the onDone function. 

This would be great functionality as then you can additionally set the pickers value after the fact rather than immediately onChange.

**Comment by Sphinxxxx** [comment]
Yes, I can certainly see that being useful. How about adding a new `onClose` callback?

**Comment by proevilz** [comment]
An `onClose` would be great.

**Comment by Sphinxxxx** [comment]
Fixed in v2.3.0
