### ISSUE TITLE
 wrong style

### ISSUE THREAD

**Issue by faultaddr** [Sphinxxxx/vanilla-picker#31]
![image](https://user-images.githubusercontent.com/18723460/82202475-8bbd2780-9934-11ea-805c-f40a370a7c2e.png)

**Comment by Sphinxxxx** [comment]
Hello! That's strange. The input and button simply use the browser's "default" font size (`1rem`). Could you make a demo where this happens? ([JSFiddle](https://jsfiddle.net/)/[CodePen](https://codepen.io/))

**Comment by faultaddr** [comment]
> Hello! That's strange. The input and button simply use the browser's "default" font size (`1rem`). Could you make a demo where this happens? ([JSFiddle](https://jsfiddle.net/)/[CodePen](https://codepen.io/))

I have solved this problem ,but I have no idea why it became like that, when i define the style forcibly as follow

```
.layout_default {

  $width-gutter: 1em;
  $width-slider: 2em;
  
  
  &.picker_wrapper {
      display: flex;
      flex-flow: row wrap;
      justify-content: space-between;
      align-items: stretch;
      
      font-size: 10px;
      width: 25em;
      input, button {
          font-size: 0.1rem!important;
      }   
  }
}
```
just provide some guides for poor guys looking for solution like me in the future.

Best wishes!

**Comment by Sphinxxxx** [comment]
Then it looks like you have some other CSS that sets a really large font size on the `html` element?

For example:

```css
html {
    font-size: 100px;
}
```
