### ISSUE TITLE
Picker appears to be semi-transparent and can see and interact with elements underneath

### ISSUE THREAD

**Issue by danielleplatt2020** [Sphinxxxx/vanilla-picker#32]
![image](https://user-images.githubusercontent.com/65593319/85281694-bc8c0180-b48a-11ea-91d4-dabc60d5b6e9.png)

These are the options that I am using:

```
pickerBackround.setOptions({
    alpha: false,
    color: '#12263F',
    popup: 'left'
});
```
Picker works as expected otherwise.

**Comment by Sphinxxxx** [comment]
The **"Select Colour"** button is rendered on top of the picker. I assume that button has `position: absolute` or `position: relative` with a high `z-index`? Try moving the picker to the foreground by including this CSS somewhere on your page:

```css
body .picker_wrapper.popup {
    z-index: 9999;
}
```
