### ISSUE TITLE
How to use vanilla-picker within forms?

### ISSUE THREAD

**Issue by ghost** [Sphinxxxx/vanilla-picker#34]
I think this question is related to the issue #20. 

If I cannot use the picker with an input filed, how can I have it in a form? 
I need to save the color that the user picks in my DB. So, I need the picker within a form. Is that possible?

**Comment by Sphinxxxx** [comment]
Keep a hidden input field in your form, and update its value when the color changes:

```javascript
var picker = new Picker({
    parent: pickerParent,
    color: 'gold',
    onChange: function(color) {
        pickerParent.style.backgroundColor = color.rgbaString;

        //Update the form's hidden input field:
        colorField.value = color.hex;
    },
});
```

https://codepen.io/Sphinxxxx/pen/KKVLxmm

**Comment by ghost** [comment]
It works! Thanks!
