### ISSUE TITLE
Option to pass window object to avoid globals

### ISSUE THREAD

**Issue by mattriley** [Sphinxxxx/vanilla-picker#36]
Hey there. I'm building a solution attempting to avoid globals as much as possible. I'm using jsdom for testing, and preferring to avoid jsdom-global. What would be helpful is if vanilla picker could accept a window object as a constructor option and use that reference internally so that vanilla picker is not relying on globals. If a window object is not passed in, it could default to the global window object. At the moment, I'm having to set these globals to get vanilla picker playing nice with my tests:

```js
global.window = window;
global.document = window.document;
global.HTMLElement = window.HTMLElement;
global.getComputedStyle = window.getComputedStyle;
```

Thanks for your consideration!

**Comment by Sphinxxxx** [comment]
Hello! Given the current structure of the library, you'd have to pass that object all over the place. I'd say your shim is the cleanest way to solve this when needed.
