### ISSUE TITLE
Prevent Hide the picker when click

### ISSUE THREAD

**Issue by HectorFenoma** [Sphinxxxx/vanilla-picker#40]
Hi, first congratulate you for so good tool you have made. Im currently using the picker and I load it inside of a modal with other options (input for text, image, etc). The thing is when i try to focus on the input, the picker hides and i lose the focus on the input. If I click again in the input, the picker shows and I lose the focus in the input again.

Is there any way to prevent or disable that option? I mean if the picker could never hide until I hide the parent (the modal) or disable the property of hide the picker when I click outside of it. 

Thanks!!

**Comment by Sphinxxxx** [comment]
Thank you!

Would it be better to show the picker as a "normal" element inside your modal, i.e. not a popup? If so, add `popup: false` to the picker options:

```javascript
var myPicker = new Picker({
    parent: ...,
    popup: false,
    ...
});
```

**Comment by HectorFenoma** [comment]
Hi Sphinxxxx, thank you so much for your reply. That's what i did, but for some reason it didn't work when i clicked the parent, still toggling the picker. What I did (maybe this could work for someone else in the same situation) was set the CSS property of the picker_wrapper in "display:block!important" and worked. Now it hides when i close the modal and if I click over the picker it doesn't toggle (at least visibly). Thank you so much again, works pretty well and looks cool! (I upload an image).
![picker](https://user-images.githubusercontent.com/53510634/102083106-9fd2f400-3e45-11eb-9b45-fd367bce9a37.jpg)
