### ISSUE TITLE
Width of picker_alpha and height of picker_hue

### ISSUE THREAD

**Issue by addsimm** [Sphinxxxx/vanilla-picker#48]
Hi,

Great package!

I'm hearing reports the two sliders are too small, so I'd like to give them more of the screen relative to picker_sl.  

I looked at the code but can't figure out how to change the relative height or width  - can anyone help?

Many thanks@

**Comment by addsimm** [comment]
For anyone else, here it is:

.layout_default .picker_slider, .layout_default .picker_selector {
    padding: .85rem
    /* sets width and height of relevant sliders */
}

**Comment by Sphinxxxx** [comment]
Looks like you fixed it, so I can close this issue?
