### ISSUE TITLE
picker.js:374 Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by Frankevisser** [Sphinxxxx/vanilla-picker#6]
Can't use it whatever element I set as parent keeps returning this error..

**Comment by Sphinxxxx** [comment]
That doesn't sound good, but I can't reproduce the error. I would need to see some code. Could you make a [JSFiddle](http://jsfiddle.net/) or similar where this happens?

**Comment by Sphinxxxx** [comment]
Wait, are you loading this library as an ES6 module in your project?

**Comment by Frankevisser** [comment]
I used the code in your tutorial and yes i'm using webpacker to configure my front-end

**Comment by Sphinxxxx** [comment]
Thanks, I think I see what I did wrong here. May I ask, which version of Webpack do you use?

**Comment by Frankevisser** [comment]
I'm using webpacker version 4.0.0.pre.3

**Comment by Sphinxxxx** [comment]
Alright, try updating vanilla-picker to v2.6 and see if that works for you.

**Comment by Frankevisser** [comment]
Thanks for your replies and fix!
